css update2
nit-gifu-gis/boar-map pull request #39
Opened 2019-12-09 14:17 UTC by nkmtykhb

css のアップデートです。

2019-12-09 15:03 UTC, lalaso2000 commented
ちょっと色々崩れてるので要確認

2019-12-09 15:08 UTC, lalaso2000 requested changes
少し全体的に微調整が必要そう
細かい不具合はレビュー参照

2019-12-09 15:25 UTC, lalaso2000 requested changes
ちょっとどこが原因かわからないけど，現在地取得ボタンが消えてる
![getLocation](https://user-images.githubusercontent.com/20383042/70448294-7faa7f80-1ae3-11ea-8c20-519548c70746.jpeg)

2019-12-09 15:25 UTC, lalaso2000 commented on components/organisms/loginForm/index.jsx
> +      <img
![IMG_793724AE894C-1](https://user-images.githubusercontent.com/20383042/70447033-6a345600-1ae1-11ea-88f1-99e0833c02ec.jpeg)
妙な位置にアイコンが来てしまう(画像はiPhoneXS)

2019-12-09 15:25 UTC, lalaso2000 commented on components/templates/Map/index.jsx
> +    <div class="footer-nav">
![footer-nav](https://user-images.githubusercontent.com/20383042/70447544-3a398280-1ae2-11ea-95b0-5350f2cccc9f.jpeg)
footer-navが表示されない(iPhoneXS Safari/Chromeで確認)

2019-12-09 15:25 UTC, lalaso2000 commented on components/templates/Map/index.jsx
> +      <AddInformationButton />
![addInformationButton](https://user-images.githubusercontent.com/20383042/70447758-9c928300-1ae2-11ea-9fbe-c4510c27a302.jpg)
AddInformationButtonが右にずれている
(複数機種で確認)

2019-12-09 15:43 UTC, junt1458 requested changes
スクリーンショットを添付します

2019-12-09 15:51 UTC, lalaso2000 requested changes

2019-12-09 15:51 UTC, lalaso2000 commented on components/organisms/infoTypeSelector/infoTypeSelector.scss
> +  border-radius: 20px 20px 0px 0px
![IMG_E8715CE066DD-1のコピー](https://user-images.githubusercontent.com/20383042/70449628-a4075b80-1ae5-11ea-97fe-8b47dcd02f04.jpeg)
URLバーが出てるから微妙な感じに見える気がする・・・
個人的にはここは素直に四角で大丈夫だと思う

2019-12-09 15:51 UTC, lalaso2000 commented on components/organisms/infoTypeSelector/infoTypeSelector.scss
> +}
![IMG_E8715CE066DD-1のコピー2](https://user-images.githubusercontent.com/20383042/70449908-255eee00-1ae6-11ea-9b26-103afc77dbb4.jpeg)
PrevButtonとNextButtonが中央からずれている(iPhone Safari/Chrome)

2019-12-09 15:51 UTC, lalaso2000 commented on components/organisms/infoTypeSelector/infoTypeSelector.scss
> +    background-color: #e87b15;
PrevButtonの背景色は白でお願いします（次へボタンを目立たせたい）

2019-12-09 15:51 UTC, lalaso2000 commented on components/organisms/infoTypeSelector/infoTypeSelector.scss
> +  margin-top: 400px;
<img width="256" alt="スクリーンショット 2019-12-10 午前0 48 24" src="https://user-images.githubusercontent.com/20383042/70450418-04e36380-1ae7-11ea-9980-cba8ab3641a3.png">
margin-topでボタンの位置を調整すると次ページ以降で悲惨なことになるので別の手段を取りたい

2019-12-09 15:54 UTC, lalaso2000 requested changes

2019-12-09 15:54 UTC, lalaso2000 commented on components/organisms/mapBase/mapBase.scss
> +    height: 100vh;
![IMG_61EBB4054508-1](https://user-images.githubusercontent.com/20383042/70450735-93f07b80-1ae7-11ea-9874-93cf44effca5.jpeg)
マップ高さが高すぎて権利関係の表示と縮尺が見切れてる

2019-12-09 15:59 UTC, junki-gnct commented
横幅が401pxを超えると大きく崩れます
![image](https://user-images.githubusercontent.com/40569974/70451205-47597000-1ae8-11ea-87f9-bff208c12d07.png)
![image](https://user-images.githubusercontent.com/40569974/70451215-4cb6ba80-1ae8-11ea-9f3c-240cef9877ee.png)

2019-12-09 16:01 UTC, junki-gnct commented
位置情報追加画面に謎の余白がある
![image](https://user-images.githubusercontent.com/40569974/70451337-8982b180-1ae8-11ea-9aec-b15c86825813.png)
![image](https://user-images.githubusercontent.com/40569974/70451348-90112900-1ae8-11ea-980a-ec490fb7c8c7.png)

2019-12-09 16:03 UTC, lalaso2000 commented
@junki-gnct 今回お願いしてるのは種類選択画面までのデザイン修正だから、位置情報追加以降は一旦スルーでお願いしたい

2019-12-09 16:03 UTC, junki-gnct commented
OKです

2019-12-09 16:08 UTC, lalaso2000 commented
@junki-gnct 横幅401px以上は多分仕様(携帯の方を優先するようにお願いした)
@nkmtykhb だけど、多分iPhoneの大きいやつだと横幅401px超えるからやっぱり要修正かな

2019-12-09 21:44 UTC, junki-gnct commented
https://www.seojuku.com/blog/responsive-mediaquery.html#201924__iOS
ブレークポイントの参考にどうぞ

2019-12-09 21:48 UTC, junki-gnct commented
iPhone XS Maxが414pxらしく、
480pxにブレークポイント設定するといいらしいです
(サイト参照)

2019-12-10 07:05 UTC, lalaso2000 requested changes
縦横比の関係で妙なことになる端末のやつはできたらでOK
残りの二つは直して欲しい

2019-12-10 07:05 UTC, lalaso2000 commented on components/atomos/addInformationButton/index.jsx
> +      <p className="label__regist">新規登録</p>
![IMG_68BB6DD254C5-1](https://user-images.githubusercontent.com/20383042/70502078-23874000-1b63-11ea-869a-551ea6921b22.jpeg)
新規登録の文字が中心に来ていない

2019-12-10 07:05 UTC, lalaso2000 commented on components/organisms/infoTypeSelector/infoTypeSelector.scss
> +    background-color: #e87b15;
![IMG_7B9F443FE560-1](https://user-images.githubusercontent.com/20383042/70503163-2c2d4580-1b66-11ea-8a4e-7a0769787a63.jpeg)
白くして欲しい

2019-12-10 07:05 UTC, lalaso2000 commented on components/organisms/mapBase/mapBase.scss
> +    height: 70vh;
![Screenshot_20191210-155215](https://user-images.githubusercontent.com/20383042/70503279-6991d300-1b66-11ea-895f-bccd118895d7.png)
縦横比の関係で妙なことになる端末が存在するかも(画像はASUS_X01AD, Zen Phone)

2019-12-10 07:47 UTC, lalaso2000 requested changes
ごめんもう一つ追加で

2019-12-10 07:47 UTC, lalaso2000 commented on components/organisms/loginForm/index.jsx
>  const LoginForm = () => {
画面の小さい端末(iPhone SE)でログインフォームが見切れてしまう

2019-12-10 07:59 UTC, lalaso2000 requested changes
もう少し・・・

2019-12-10 07:59 UTC, lalaso2000 commented on components/templates/Map/index.jsx
> +    <div className="footer-nav">
![IMG_C1DE17F26760-1](https://user-images.githubusercontent.com/20383042/70506557-f724f100-1b6d-11ea-89c5-610549dd2c61.jpeg)
下が見切れる

2019-12-10 07:59 UTC, lalaso2000 commented on components/atomos/addInformationButton/index.jsx
> +      <button className="regist__button" onClick={OnClick}>
ボタンの当たり判定が画面の横幅いっぱいまである

2019-12-10 12:34 UTC, lalaso2000 reviewed
一旦これでokにします
マージすると他のページのレイアウトに影響するので一旦保留、戸松くんの #16 が完了したあと、他のページのレイアウトも完成させてからマージします

2019-12-12 09:31 UTC, lalaso2000 requested changes
ほぼ問題なしです
一点だけ

2019-12-12 09:31 UTC, lalaso2000 commented on components/organisms/mapForAddInfo/mapForAddInfo.scss
> +  height: 70vh;
![IMG_2C858EDC4723-1](https://user-images.githubusercontent.com/20383042/70699273-35f0ad80-1d0c-11ea-92ca-3a85e4b307a8.jpeg)
縮尺と権利表示が見切れてる

2019-12-12 09:33 UTC, lalaso2000 commented
他の登録画面との兼ね合いでマージはまだ先送りにします

2019-12-22 11:56 UTC, lalaso2000 approved these changes
モバイルはとりあえず全画面対応完了
PCはとりあえずモバイルと同じ表示になるようにしました

2019-12-22 12:24 UTC, junt1458 requested changes
ざっと見た感じこの３点だけです 🙏 

![1577017123924](https://user-images.githubusercontent.com/40569974/71321714-09eddd00-2501-11ea-9ced-212e95e7f280.jpg)
ワクチンの書き込み権限がないアカウントだと最後の要素に下線がない

![1577017147517](https://user-images.githubusercontent.com/40569974/71321720-1a05bc80-2501-11ea-988d-7ed6f9a92f06.jpg)
位置指定画面のマップの下に空白がある

<img width="743" alt="スクリーンショット 2019-12-22 21 23 36" src="https://user-images.githubusercontent.com/40569974/71321749-6650fc80-2501-11ea-9cee-06d1f688625c.png">
ログイン画面の背景のサイズが固定のため、縦に大きすぎたり逆に小さかったりする

2019-12-22 12:37 UTC, junki-gnct commented
@lalaso2000 上の3点、確認お願いします 🙏

2019-12-22 15:46 UTC, lalaso2000 commented
@junki-gnct 
一つ目については解消
二つ目と三つ目に関してはかなり大規模な修正をかけないと直らない雰囲気

2019-12-22 15:48 UTC, lalaso2000 commented
二つ目：ヘッダ＋説明＋フッタの高さを取得して引き算する必要がある
三つ目：bodyのbackground-colorをいじると何故か全体に適用されてしまう

2019-12-22 15:51 UTC, lalaso2000 commented
これcssファイルをインポートしてるしてないに関わらず全部のcssがグローバルに適用されるっぽい
何か間違えてるのかも…

2019-12-22 21:50 UTC, junki-gnct commented
cssの読み込み問題は少し調べておきます
一旦マージして、別issue建てておく感じでいいと思います👍

2019-12-22 23:49 UTC, merged