画像アップロード機能の実装 #74
nit-gifu-gis/boar-map pull request #78
Opened 2020-04-20 03:00 UTC by junki-gnct

#74 デザインは未完です。

機能的には実装完了したので、一旦マージお願いします 🙏 

↓
https://app-gis-dev.junki-t.net/

(画像サーバーも同一サーバー内で稼働中
 https://api-gis-dev.junki-t.net/)

2020-04-20 11:17 UTC, lalaso2000 commented
動作確認しました
問題なさそう
デザイン明日中に仕上げます

2020-04-20 11:26 UTC, lalaso2000 commented
登録画面で画像をアップロード→確認画面に行く→登録画面に戻る→確認画面→登録
の順に画像遷移すると，上のフォームのデータは保持されるが，画像だけ保持されない

2020-04-20 11:27 UTC, lalaso2000 commented
でもこれ処理のタイミング的に難しいような気もする…？
確認画面に行く段階で画像を一回アップロードするのも気になるけど，こうせざるを得ないような気もする
直せたら直したい

2020-04-20 11:30 UTC, junki-gnct commented
確認画面の時点で一回アップロードしてるのは、Routerで次画面にFormDataを渡してみたんですけど、アップロードできなかったっぽいんですよね...
もしかしたら別の方法でできるのかもしれないんですけど、僕にはよくわからなかったので、今は確認画面で一旦アップロードして、登録時にアップロードしたファイルを公開するという処理にしてあります。

2020-04-20 11:36 UTC, lalaso2000 requested changes
もしかしたらこれかも

2020-04-20 11:36 UTC, lalaso2000 commented on components/templates/AddInfo/index.jsx
> +    this.state.formData = data;
ここ
```[js]
this.setState({formData: data});
```
だと思う

2020-04-20 11:45 UTC, junki-gnct commented on components/templates/AddInfo/index.jsx
> +    this.state.formData = data;
this.setState({formData; data});とthis.state.formData = data;の違いって、確か再レンダリングするかしないかの違いだったと思うんですけど、どうなんでしょう

2020-04-20 11:54 UTC, lalaso2000 commented on components/templates/AddInfo/index.jsx
> +    this.state.formData = data;
[ここ](https://ja.reactjs.org/docs/state-and-lifecycle.html)見てると，確かに

> 例えば、以下のコードではコンポーネントは再レンダーされません

だから再レンダーはされないよってしか言ってないかも


下に

> this.state に直接代入してよい唯一の場所はコンストラクタです。

って書いてあるから，コンストラクタ以外ではsetState使うと思ってた

2020-04-20 12:30 UTC, lalaso2000 commented
formDataは辞書型じゃないから次ページへのqueryで持ち越すことは出来なさそう
[indexedDBを使えばローカルに画像を保存して次のページで読み出せる…かも？](https://blog.htmlhifive.com/2018/06/06/indexed-db/)

2020-04-21 14:09 UTC, lalaso2000 approved these changes

2020-04-21 15:39 UTC, junki-gnct commented
処理改善のissueは別で立てるので、一旦マージします。

あと、
https://app-gis-dev.junki-t.net/ の自動デプロイのブランチを
feature/74からmasterに変更します。

2020-04-21 15:40 UTC, merged

2020-04-21 15:47 UTC, junki-gnct commented
処理改善のissueは別で立てるので、一旦マージします。

あと、
https://app-gis-dev.junki-t.net/ の自動デプロイのブランチを
feature/74からmasterに変更します。